name: companera
description: An app to detect falls, recognize sign language and read text from images
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  sensors_plus: ^1.3.0
  tflite:
    git: https://github.com/anohene1/flutter_tflite.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/