name: companera
description: An app to detect falls, recognize sign language and read text from images
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.18
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  sensors_plus: ^1.3.0
  tflite:
    git: https://github.com/anohene1/flutter_tflite.git
  flutter_platform_alert: ^0.2.2
  line_icons: ^2.0.1
  salomon_bottom_bar: ^3.3.0
  fl_chart: ^0.50.1
  google_maps_flutter: ^2.1.3
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  google_ml_vision: 0.0.6
  flutter_tts: ^3.4.0
  flutter_background_service: ^2.1.3
  background_location:
    git: https://github.com/kleeb/background_location.git
  fluttercontactpicker: ^4.6.0
  flutter_slidable: ^1.3.0
  awesome_notifications: ^0.6.21
  location: ^4.4.0
  intl: ^0.17.0
  permission_handler: ^10.0.0
  background_sms: ^0.0.4
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/