// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAo6-mVaDR017f0qm3JQmQ4US23RYRnKo',
    appId: '1:736882067229:android:2c8228361e59846b3c03f4',
    messagingSenderId: '736882067229',
    projectId: 'companera-a51f4',
    storageBucket: 'companera-a51f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMlZtPfMc_iw9vlJ4Qvhh0Dja5czv--Y',
    appId: '1:736882067229:ios:93a9bf7fa4bf66f13c03f4',
    messagingSenderId: '736882067229',
    projectId: 'companera-a51f4',
    storageBucket: 'companera-a51f4.appspot.com',
    iosClientId: '736882067229-bjmfrmfsm3o58u28hdedralb2mthcpdg.apps.googleusercontent.com',
    iosBundleId: 'com.anohene.companera',
  );
}
